### ISSUE TITLE
[BUG] skipLibCheck causes compilation to fail

### ISSUE THREAD

**Issue by antspk** [iamolegga/nestjs-pino#680]
[x] I've read [the docs of nestjs-pino](https://github.com/iamolegga/nestjs-pino/blob/master/README.md)

[x] I've read [the docs of pino](https://getpino.io/#/)

[x] I couldn't find the same [open issue of nestjs-pino](https://github.com/iamolegga/nestjs-pino/issues)

**What is the current behavior?**
When `skipLibCheck` is disabled in `tsconfig.json` compilation fails.
```shell
node_modules/nestjs-pino/params.d.ts:3:10 - error TS2614: Module '"pino"' has no exported member 'DestinationStream'. Did you mean to use 'import DestinationStream from "pino"' instead?

3 import { DestinationStream } from 'pino';
           ~~~~~~~~~~~~~~~~~

node_modules/nestjs-pino/params.d.ts:6:18 - error TS2694: Namespace '"/nestjs-pino-bug/node_modules/pino/pino"' has no exported member 'Logger'.

6     logger: pino.Logger;
                   ~~~~~~

node_modules/nestjs-pino/params.d.ts:13:25 - error TS2694: Namespace '"/nestjs-pino-bug/node_modules/pino-http/index"' has no exported member 'Options'.

13     pinoHttp?: pinoHttp.Options | DestinationStream | [pinoHttp.Options, DestinationStream];
                           ~~~~~~~

node_modules/nestjs-pino/params.d.ts:13:65 - error TS2694: Namespace '"/nestjs-pino-bug/node_modules/pino-http/index"' has no exported member 'Options'.

13     pinoHttp?: pinoHttp.Options | DestinationStream | [pinoHttp.Options, DestinationStream];
                                                                   ~~~~~~~

node_modules/nestjs-pino/PinoLogger.d.ts:3:38 - error TS2694: Namespace '"/nestjs-pino-bug/node_modules/pino/pino"' has no exported member 'BaseLogger'.

3 declare type PinoMethods = Pick<pino.BaseLogger, 'trace' | 'debug' | 'info' | 'warn' | 'error' | 'fatal'>;
                                       ~~~~~~~~~~

node_modules/nestjs-pino/PinoLogger.d.ts:11:32 - error TS2694: Namespace '"/nestjs-pino-bug/node_modules/pino/pino"' has no exported member 'Logger'.

11     static readonly root: pino.Logger;
                                  ~~~~~~

node_modules/nestjs-pino/PinoLogger.d.ts:29:24 - error TS2694: Namespace '"/nestjs-pino-bug/node_modules/pino/pino"' has no exported member 'Logger'.

29     get logger(): pino.Logger;
                          ~~~~~~

node_modules/nestjs-pino/PinoLogger.d.ts:30:25 - error TS2694: Namespace '"/nestjs-pino-bug/node_modules/pino/pino"' has no exported member 'Bindings'.

30     assign(fields: pino.Bindings): void;
```

**What is the expected behavior?**
Library should work independently from `skipLibCheck` config flag.

**Please provide minimal example repo. Without it this issue will be closed**
https://github.com/antspk/nestjs-pino-bug

**Please mention other relevant information such as Node.js version and Operating System.**
node v16.13.0
macos 12.0.1

**Comment by iamolegga** [comment]
could be caused by https://github.com/DefinitelyTyped/DefinitelyTyped/pull/57023

will check soon

**Comment by tomtastico** [comment]
Having this problem too

**Comment by tomoat** [comment]
me too

**Comment by iamolegga** [comment]
OK, so pino-team had decided to move the types from `@types/pino` to the lib's `.d.ts` file. [Without backward compatibility](https://github.com/pinojs/pino/issues/910#issuecomment-952861516)

Subscribe to [this issue](https://github.com/pinojs/pino/issues/1193) and switch `skipLibCheck` until it's fixed.

As this is not a bug of the current library I'm closing, but will pin it until it's fixed.

**Comment by FredericEspiau** [comment]
@iamolegga https://github.com/pinojs/pino/issues/1193#issuecomment-981633962 it's been fixed

**Comment by iamolegga** [comment]
@FredericEspiau thanks, already seen this too. Will check soon

**Comment by iamolegga** [comment]
It looks like not everything was fixed https://github.com/iamolegga/nestjs-pino/runs/4361882493?check_suite_focus=true 
WIll check manually when I get time on this

**Comment by iamolegga** [comment]
finally, all the types are fixed in v2.4.0. Big thanks to @jarcodallo . Unpinning this issue

**Comment by FredericEspiau** [comment]
Thanks for the awesome work
